### ISSUE TITLE
how i make plugins in python or c

### ISSUE THREAD

**Issue by arydevy** [ClassiCube/ClassiCube-Plugins#2]

**Comment by arydevy** [comment]
is a way that i can make client plugins in c 
i also know python

**Comment by arydevy** [comment]
some tuts

**Comment by UnknownShadow200** [comment]
I sort of documented how make a basic one at https://github.com/UnknownShadow200/ClassiCube/blob/master/doc/plugin-dev.md

**Comment by arydevy** [comment]
is there a spreatsheet with the avalebl methods?

**Comment by UnknownShadow200** [comment]
Anything in the .h files that are marked as CC_API or CC_VAR can be used by plugins. [Current list](https://gist.github.com/UnknownShadow200/e7dba6ebbc8197736a3aff923625b6f2)

**Comment by arydevy** [comment]
these are client or server plugins

**Comment by UnknownShadow200** [comment]
Client
