### ISSUE TITLE
how to make a server softwere in python or c?

### ISSUE THREAD

**Issue by arydevy** [ClassiCube/ClassiCube-Plugins#3]

**Comment by arydevy** [comment]
i want to make my server softwere becouse here are lot of but not alll are good enoth for me or the plugin coding uses languages that idk
is posible and basics haw i make a basic one so i earn and make a better one

**Comment by UnknownShadow200** [comment]
You need to read through https://wiki.vg/Classic_Protocol and understand everything that is said on that page at least

**Comment by arydevy** [comment]
and i use soket progrming for this ?
also how you conect to servers if you use the the classicube user and what are the Fallback IDs?

**Comment by UnknownShadow200** [comment]
Yes, you need TCP sockets

I'm not sure what fallback IDs is referring to

**Comment by arydevy** [comment]
> Yes, you need TCP sockets
> 
> I'm not sure what fallback IDs is referring to

to what?

**Comment by arydevy** [comment]
everywere are is like this 0x00  how i use them?

**Comment by UnknownShadow200** [comment]
For client -> server packets:
```
packet_id = read_byte_from_socket();
if (packet_id == 0x00) handle_server_identification();
if (packet_id == 0x05) handle_set_block();
etc
```

For server -> client packets:
```
write_level_init() {
  char data[1];
  data[0] = 0x02;
  write_to_socket(data, 1);
}
etc
```
