### ISSUE TITLE
Attempting to download pre-compiled plugins ends up in a Page error

### ISSUE THREAD

**Issue by Adamixdex** [ClassiCube/ClassiCube-Plugins#7]
"Error loading page
It looks like your internet connection is down. Please check it."
This is definetly not a me issue because i have a more-than-functional router and i tested it on diffrent devices.
Possibly removed .md??

this happens on downloading every plugin from the .md files, but downloading from the filesystem itself (eg. `git clone https://github.com/ClassiCube/ClassiCube-Plugins.git`) does not fail.

**Comment by UnknownShadow200** [comment]
If you right click a download link > Open in new tab, it downloads fine

Just clicking the download link is producing that confusing error message due to failing a CORS check
![image](https://github.com/user-attachments/assets/88641a21-9600-4740-913c-d387f037acd2)

**Comment by Adamixdex** [comment]
Alright, i just thought it would be misleading for new and not advanced users.

**Comment by UnknownShadow200** [comment]
It is confusing though, and I do plan on changing it when I get around to it

**Comment by UnknownShadow200** [comment]
It has been fixed now, and you can now just click on the link to download plugins.
